const products = [
                            //! RELOJES COMPETICION
    {
        id:10,
        name: 'Reloj Presion de turbo ProSport',
        price: 45000,
        brand: 'prosport',
        img: "./assets/images/productos/relojes/psturbodig.webp",
        amount: 1,
        type: "reloj",
    },
    {
        id:11,
        name: 'Reloj Presion de turbo Orlan Rober',
        price: 18000,
        brand: 'orlan rober',
        img: "./assets/images/productos/relojes/psturbo.webp",
        amount: 1,
        type: "reloj",
    },
    {
        id:12,
        name: 'Wideband AEM X-Series',
        price: 120000,
        brand: 'AEM',
        img: "./assets/images/productos/relojes/aemx.jpg",
        amount: 1,
        type: "reloj",
    },
    {
        id:13,
        name: 'Wideband Innovate MTX-L',
        price: 140000,
        brand: 'prosport',
        img: "./assets/images/productos/relojes/innmtx.jpg",
        amount: 1,
        type: "reloj",
    },

                            //! TURBOCOMPRESORES
    {
        id:20,
        name: 'Turbo Garrett T3 Bipulsativo',
        price: 380000,
        brand: 'garrett',
        img: "./assets/images/productos/turbos/t3.webp",
        amount: 1,
        type: "turbo",
    },
    {
        id:21,
        name: 'Turbo Master Power Racing R615/2',
        price: 300000,
        brand: 'master power',
        img: "./assets/images/productos/turbos/r615.webp",
        amount: 1,
        type: "turbo",
    },
    {
        id:22,
        name: 'Turbo Garrett GT2560R',
        price: 300000,
        brand: 'master power',
        img: "./assets/images/productos/turbos/gt2554.jpg",
        amount: 1,
        type: "turbo",
    },
    {
        id:23,
        name: 'Turbo Garrett GT2871R',
        price: 300000,
        brand: 'master power',
        img: "./assets/images/productos/turbos/gt2871.jpg",
        amount: 1,
        type: "turbo",
    },

                            //! REFRIGERACION
    {
        id:30,
        name: 'Intercooler BMW N55 F',
        price: 500000,
        brand: 'ftx',
        img: "./assets/images/productos/refrigeracion/n55.webp",
        amount: 1,
        type: "refri",
    },
    {
        id:31,
        name: 'Intercooler BMW N54 335i',
        price: 430000,
        brand: 'ftx',
        img: "./assets/images/productos/refrigeracion/n54.webp",
        amount: 1,
        type: "refri",
    },
    {
        id:32,
        name: 'Intercooler FTX 60x23 cm',
        price: 400000,
        brand: 'ftx',
        img: "./assets/images/productos/refrigeracion/intercooler-ftx.webp",
        amount: 1,
        type: "refri",
    },

                            //! INYECCION
    {
        id:40,
        name: 'Fueltech FT600',
        price: 990000,
        brand: 'fueltech',
        img: "./assets/images/productos/inyeccion/ft600.jpg",
        amount: 1,
        type: "ecu",
    },
    {
        id:41,
        name: 'Fueltech FT550',
        price: 800000,
        brand: 'fueltech',
        img: "./assets/images/productos/inyeccion/ft550.png",
        amount: 1,
        type: "ecu",
    },
    {
        id:42,
        name: 'Fueltech FT450',
        price: 500000,
        brand: 'fueltech',
        img: "./assets/images/productos/inyeccion/ft450.png",
        stock: 15,
        amount: 1,
        type: "ecu",
    },
    {
        id:43,
        name: 'Fueltech FT300',
        price: 300000,
        brand: 'fueltech',
        img: "./assets/images/productos/inyeccion/ft300.jpg",
        amount: 1,
        type: "ecu",
    },

                            //! LUBRICANTES
    {
        id:50,
        name: 'Motul 300v Le Mans 20W60',
        price: 26000,
        brand: 'motul',
        img: "./assets/images/productos/lubricantes/20w60.jpeg",
        amount: 1,
        type: "lubricante",
    },
    {
        id:51,
        name: 'Motul 300v Le Mans 10W60',
        price: 18000,
        brand: 'motul',
        img: "./assets/images/productos/lubricantes/10w60.jpeg",
        amount: 1,
        type: "lubricante",
    },
    {
        id:52,
        name: 'Motul 300v Competition 15W50',
        price: 20000,
        brand: 'motul',
        img: "./assets/images/productos/lubricantes/15w50.jpeg",
        amount: 1,
        type: "lubricante",
    },
    {
        id:53,
        name: 'Motul 300v Competition 5W40',
        price: 24000,
        brand: 'motul',
        img: "./assets/images/productos/lubricantes/5w40.jpeg",
        amount: 1,
        type: "lubricante",
    },
    {
        id:54,
        name: 'Motul Classics 90s 10W30',
        price: 30000,
        brand: 'motul',
        img: "./assets/images/productos/lubricantes/10w30.jpg",
        amount: 1,
        type: "lubricante",
    },
    {
        id:55,
        name: 'Motul Classics 80s 10W40',
        price: 32000,
        brand: 'motul',
        img: "./assets/images/productos/lubricantes/10w40.jpg",
        amount: 1,
        type: "lubricante",
    },
]