const products = [
                            //! RELOJES COMPETICION
    {
        id:10,
        name: 'Reloj Presion de turbo ProSport',
        price: 45000,
        brand: 'prosport',
        img: "./assets/images/productos/relojes/psturbodig.webp",
        amount: 1,
        type: 1,
    },
    {
        id:11,
        name: 'Reloj Presion de turbo Orlan Rober',
        price: 18000,
        brand: 'orlan rober',
        img: "./assets/images/productos/relojes/psturbo.webp",
        amount: 1,
        type: 1,
    },

                            //! TURBOCOMPRESORES
    {
        id:20,
        name: 'Turbo Garrett T3 Bipulsativo',
        price: 380000,
        brand: 'garrett',
        img: "./assets/images/productos/turbos/t3.webp",
        amount: 1,
        type: 2,
    },
    {
        id:21,
        name: 'Turbo Master Power Racing R615/2',
        price: 300000,
        brand: 'master power',
        img: "./assets/images/productos/turbos/t3.webp",
        amount: 1,
        type: 2,
    },

                            //! REFRIGERACION
    {
        id:30,
        name: 'Intercooler BMW N55 F',
        price: 500000,
        brand: 'ftx',
        img: "./assets/images/productos/refrigeracion/intercooler-ftx.webp",
        amount: 1,
        type: 3,
    },
    {
        id:31,
        name: 'Intercooler BMW N54 335i',
        price: 430000,
        brand: 'ftx',
        img: "./assets/images/productos/refrigeracion/intercooler-ftx.webp",
        amount: 1,
        type: 3,
    },
    {
        id:32,
        name: 'Intercooler FTX 60x23 cm',
        price: 400000,
        brand: 'ftx',
        img: "./assets/images/productos/refrigeracion/intercooler-ftx.webp",
        amount: 1,
        type: 3,
    },

                            //! INYECCION
    {
        id:40,
        name: 'Fueltech FT600',
        price: 990000,
        brand: 'fueltech',
        img: "./assets/images/productos/inyeccion/ft450.webp",
        amount: 1,
        type: 4,
    },
    {
        id:41,
        name: 'Fueltech FT550',
        price: 800000,
        brand: 'fueltech',
        img: "./assets/images/productos/inyeccion/ft450.webp",
        amount: 1,
        type: 4,
    },
    {
        id:42,
        name: 'Fueltech FT450',
        price: 500000,
        brand: 'fueltech',
        img: "./assets/images/productos/inyeccion/ft450.webp",
        stock: 15,
        amount: 1,
        type: 4,
    },
    {
        id:43,
        name: 'Fueltech FT300',
        price: 300000,
        brand: 'fueltech',
        img: "./assets/images/productos/inyeccion/ft450.webp",
        amount: 1,
        type: 4,
    },

                            //! LUBRICANTES
    {
        id:50,
        name: 'Motul X-Clean 5w30 x5 Lts',
        price: 26000,
        brand: 'motul',
        img: "./assets/images/productos/lubricantes/motul-300v.webp",
        amount: 1,
        type: 5,
    },
    {
        id:51,
        name: 'Aceite Motul 300V 20w60',
        price: 18000,
        brand: 'motul',
        img: "./assets/images/productos/lubricantes/motul-300v.webp",
        amount: 1,
        type: 5,
    },
]